-- MySQL Script generated by MySQL Workbench
-- lun 29 mar 2021 18:45:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET armscii8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`programming_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`programming_languages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`programming_languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(256) NULL,
  `last_login` DATETIME NULL,
  `age` INT NULL,
  `country` VARCHAR(45) NULL,
  `background` VARCHAR(45) NULL,
  `preferred_programming_languages` INT NULL,
  INDEX `fk_User_Programming language1_idx` (`preferred_programming_languages` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_User_Programming language1`
    FOREIGN KEY (`preferred_programming_languages`)
    REFERENCES `mydb`.`programming_languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Login Info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Login Info` (
  `login` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Lastlogin` DATETIME NULL,
  `User_idUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`, `User_idUser`),
  INDEX `fk_Login Info_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Login Info_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`challenges` ;

CREATE TABLE IF NOT EXISTS `mydb`.`challenges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `level` INT NULL,
  `instructions` LONGTEXT NULL,
  `test_data` LONGTEXT NULL,
  `solution` LONGTEXT NULL,
  `hint` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`languages_challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`languages_challenges` ;

CREATE TABLE IF NOT EXISTS `mydb`.`languages_challenges` (
  `challenges_id` INT NOT NULL,
  `programming_languages_id` INT NOT NULL,
  `example_code` LONGTEXT NULL,
  PRIMARY KEY (`challenges_id`, `programming_languages_id`),
  INDEX `fk_Challenge_has_Programming language_Programming language1_idx` (`programming_languages_id` ASC) VISIBLE,
  INDEX `fk_Challenge_has_Programming language_Challenge_idx` (`challenges_id` ASC) VISIBLE,
  CONSTRAINT `fk_Challenge_has_Programming language_Challenge`
    FOREIGN KEY (`challenges_id`)
    REFERENCES `mydb`.`challenges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Challenge_has_Programming language_Programming language1`
    FOREIGN KEY (`programming_languages_id`)
    REFERENCES `mydb`.`programming_languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`challenges_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`challenges_stats` ;

CREATE TABLE IF NOT EXISTS `mydb`.`challenges_stats` (
  `challenges_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `tries` INT NULL,
  `solved` TINYINT(1) NULL,
  `programming_languages_id` INT NOT NULL,
  PRIMARY KEY (`challenges_id`, `users_id`, `programming_languages_id`),
  INDEX `fk_Challenge_has_User_User1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_Challenge_has_User_Challenge1_idx` (`challenges_id` ASC) VISIBLE,
  INDEX `fk_challenges_stats_programming_languages1_idx` (`programming_languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_Challenge_has_User_Challenge1`
    FOREIGN KEY (`challenges_id`)
    REFERENCES `mydb`.`challenges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Challenge_has_User_User1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_challenges_stats_programming_languages1`
    FOREIGN KEY (`programming_languages_id`)
    REFERENCES `mydb`.`programming_languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories_challenges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories_challenges` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories_challenges` (
  `categories_id` INT NOT NULL,
  `challenges_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `challenges_id`),
  INDEX `fk_Category_has_Challenge_Challenge1_idx` (`challenges_id` ASC) VISIBLE,
  INDEX `fk_Category_has_Challenge_Category1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Category_has_Challenge_Category1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Challenge_Challenge1`
    FOREIGN KEY (`challenges_id`)
    REFERENCES `mydb`.`challenges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
